// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVIRMFZLh5QngwvGyEPecTdQiRCDKeFa8',
    appId: '1:169515770563:android:f3ab821a8c6ea39eadf876',
    messagingSenderId: '169515770563',
    projectId: 'desafio-toro-b2273',
    storageBucket: 'desafio-toro-b2273.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6ySk0Ye74lcTcUsl9S40wkiJWgX5uh3U',
    appId: '1:169515770563:ios:e0335d2797e2a3c4adf876',
    messagingSenderId: '169515770563',
    projectId: 'desafio-toro-b2273',
    storageBucket: 'desafio-toro-b2273.appspot.com',
    iosClientId: '169515770563-583d1cktau2otqmv8v8kgt2c51c2mhki.apps.googleusercontent.com',
    iosBundleId: 'com.example.toroApp',
  );
}
